import classes from "./Home.module.css";

const TermsOfService = () => {
  return (
    <div className={classes.aboutContainer}>
      <div className={classes.leftSection}>
        <div className={classes.aboutTextSection}>
          <div className={classes.tostextContainer}>
            <h4 className={classes.title}>Terms of Service</h4>
            <p className={classes.formSubText}>
              Disclaimer and Terms of Service for DocuMend.
            </p>
            <p>
              Welcome to DocuMend! By using our website and services, you agree
              to the following terms:
            </p>
            <ul className={classes.bulletList}>
              <li>
                <p>
                  <span>1. Acceptance of Terms</span> {`By accessing and using
                  DocuMend ("the Service"), you acknowledge that you have
                  read, understood, and agreed to these terms. If you do not
                  agree with these terms, please refrain from using our website
                  and services.`}
                </p>
              </li>
              <li>
                <p>
                  <span>2. Accuracy Verification</span> {`While DocuMend strives to provide accurate and reliable documentation assistance, users are solely responsible for verifying the accuracy and completeness of the generated reports. The AI-generated content should not be considered as a substitute for professional judgment and expertise.`}
                </p>
              </li>
              <li>
                <p>
                  <span>3. Premium Services</span> {`The Service offers a Premium version that is subject to fees. By choosing to use DocuMend Premium, you agree to pay all fees associated with it, as described on our website at the time of purchase. Fees are non-refundable, even for partial periods of service. We reserve the right to change our fees at any time.`}
                </p>
              </li>
              <li>
                <p>
                  <span>4. Limited Liability</span> {`DocuMend and its developers shall not be liable or held accountable for any damages, losses, or consequences arising from the use of our services, including but not limited to errors or omissions in the generated content.`}
                </p>
              </li>
              <li>
                <p>
                  <span>5. No Legal or Medical Advice</span> {`The information provided by DocuMend is intended for general informational purposes only and should not be construed as legal, medical, or professional advice. Users should always consult with qualified professionals for specific legal, medical, or other professional guidance.`}
                </p>
              </li>
              <li>
                <p>
                  <span>6. Intellectual Property</span> {`All content generated by DocuMend remains the intellectual property of DocuMend and its developers. Users may use the content for personal and non-commercial purposes but are prohibited from using, reproducing, or distributing the content for commercial use without explicit permission.`}
                </p>
              </li>
              <li>
                <p>
                  <span>7. User Conduct</span> {`Users of DocuMend must adhere to ethical standards and professional guidelines while using our services. Any misuse, abuse, or violation of applicable laws and regulations may result in termination of access to our website.`}
                </p>
              </li>
              <li>
                <p>
                  <span>8. Service Availability</span> {`DocuMend aims to provide a reliable and available service, but we do not guarantee uninterrupted access to the website and its features. Temporary disruptions, maintenance, or technical issues may occur.`}
                </p>
              </li>
              <li>
                <p>
                  <span>9. Modification of Terms</span> {`DocuMend reserves the right to modify, update, or change these terms of service at any time. It is the user's responsibility to review the terms periodically for any updates.`}
                </p>
              </li>
              <li>
                <p>
                  <span>10. Governing Law</span> {`These Terms of Service will be governed by and construed in accordance with the laws of the jurisdiction in which the company operates.`}
                </p>
              </li>



            </ul>
            <div className={classes.buttonContainer}>
              <button>Start Chating</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
